server:
  servlet:
    session:
      cookie:
        secure: true

spring:
  datasource:
    url: jdbc:postgresql://db:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1

