ALTER TABLE ai_api_calls
    DROP CONSTRAINT IF EXISTS ai_api_calls_purpose_check;

ALTER TABLE ai_api_calls
    ADD CONSTRAINT ai_api_calls_purpose_check
        CHECK (purpose IN ('GENERATION', 'REPAIR', 'VALIDATION', 'SOURCE_DISCOVERY'));

CREATE TABLE source_briefs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_date DATE UNIQUE NOT NULL,
    status VARCHAR(20) NOT NULL,
    model VARCHAR(100) NOT NULL,
    briefing_text TEXT,
    error_message TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT ck_source_briefs_status
        CHECK (status IN ('READY', 'FAILED'))
);

CREATE TABLE content_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_brief_id BIGINT NOT NULL,
    passage_position SMALLINT NOT NULL,
    title VARCHAR(500) NOT NULL,
    publisher VARCHAR(200),
    published_on DATE,
    source_url TEXT NOT NULL,
    summary TEXT,
    retrieved_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    verified BOOLEAN DEFAULT TRUE NOT NULL,

    CONSTRAINT fk_content_sources_brief
        FOREIGN KEY (source_brief_id) REFERENCES source_briefs (id) ON DELETE CASCADE,
    CONSTRAINT ck_content_sources_position
        CHECK (passage_position BETWEEN 1 AND 3),
    CONSTRAINT ux_content_sources_brief_url
        UNIQUE (source_brief_id, source_url)
);

CREATE INDEX ix_content_sources_brief_position
    ON content_sources (source_brief_id, passage_position);

CREATE TABLE passage_sources (
    passage_id BIGINT NOT NULL,
    content_source_id BIGINT NOT NULL,
    PRIMARY KEY (passage_id, content_source_id),

    CONSTRAINT fk_passage_sources_passage
        FOREIGN KEY (passage_id) REFERENCES passages (id) ON DELETE CASCADE,
    CONSTRAINT fk_passage_sources_source
        FOREIGN KEY (content_source_id) REFERENCES content_sources (id) ON DELETE CASCADE
);

CREATE TABLE operation_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(40) NOT NULL,
    status VARCHAR(20) NOT NULL,
    message TEXT,
    details_json JSONB,
    started_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    completed_at TIMESTAMPTZ,

    CONSTRAINT ck_operation_events_status
        CHECK (status IN ('STARTED', 'SUCCESS', 'FAILED'))
);

CREATE INDEX ix_operation_events_type_started
    ON operation_events (event_type, started_at DESC);
