CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_name VARCHAR(50) UNIQUE NOT NULL,
    display_name VARCHAR(50) NOT NULL,
    pin_hash VARCHAR(100) NOT NULL,
    app_role VARCHAR(20) DEFAULT 'USER' NOT NULL,
    enabled BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_login_at TIMESTAMPTZ,

    CONSTRAINT ck_app_users_app_role
        CHECK (app_role IN ('USER', 'ADMIN'))
);

CREATE TABLE study_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    created_by_user_id BIGINT NOT NULL,
    enabled BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_study_groups_created_by
        FOREIGN KEY (created_by_user_id) REFERENCES app_users (id)
);

CREATE TABLE group_members (
    group_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL,
    joined_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,

    PRIMARY KEY (group_id, user_id),

    CONSTRAINT fk_group_members_group
        FOREIGN KEY (group_id) REFERENCES study_groups (id),

    CONSTRAINT fk_group_members_user
        FOREIGN KEY (user_id) REFERENCES app_users (id),

    CONSTRAINT ck_group_members_role
        CHECK (role IN ('OWNER', 'MEMBER'))
);

CREATE UNIQUE INDEX ux_group_members_one_owner
    ON group_members (group_id)
    WHERE role = 'OWNER';

CREATE INDEX ix_group_members_user
    ON group_members (user_id);

CREATE TABLE group_invites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    code_hash VARCHAR(100) NOT NULL,
    enabled BOOLEAN DEFAULT TRUE NOT NULL,
    expires_at TIMESTAMPTZ,
    max_uses INTEGER,
    used_count INTEGER DEFAULT 0 NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_group_invites_group
        FOREIGN KEY (group_id) REFERENCES study_groups (id),

    CONSTRAINT fk_group_invites_created_by
        FOREIGN KEY (created_by_user_id) REFERENCES app_users (id),

    CONSTRAINT ck_group_invites_max_uses
        CHECK (max_uses IS NULL OR max_uses > 0),

    CONSTRAINT ck_group_invites_used_count
        CHECK (used_count >= 0),

    CONSTRAINT ck_group_invites_used_count_limit
        CHECK (max_uses IS NULL OR used_count <= max_uses)
);

CREATE UNIQUE INDEX ux_group_invites_enabled_code_hash
    ON group_invites (code_hash)
    WHERE enabled = TRUE;

CREATE TABLE quiz_sets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    challenge_date DATE,
    difficulty VARCHAR(30) DEFAULT 'HIGH_SCHOOL_GRADE_3' NOT NULL,
    status VARCHAR(20) NOT NULL,
    ai_provider VARCHAR(30),
    ai_model VARCHAR(100),
    prompt_version VARCHAR(30),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    published_at TIMESTAMPTZ,

    CONSTRAINT ck_quiz_sets_difficulty
        CHECK (difficulty IN ('HIGH_SCHOOL_GRADE_3')),

    CONSTRAINT ck_quiz_sets_status
        CHECK (status IN ('DRAFT', 'REVIEWED', 'PUBLISHED', 'REJECTED'))
);

CREATE UNIQUE INDEX ux_quiz_sets_published_date
    ON quiz_sets (challenge_date)
    WHERE status = 'PUBLISHED';

CREATE TABLE passages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_set_id BIGINT NOT NULL,
    position SMALLINT NOT NULL,
    title VARCHAR(300),
    content TEXT NOT NULL,
    topic VARCHAR(100),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_passages_quiz_set
        FOREIGN KEY (quiz_set_id) REFERENCES quiz_sets (id),

    CONSTRAINT ux_passages_quiz_position
        UNIQUE (quiz_set_id, position),

    CONSTRAINT ck_passages_position
        CHECK (position BETWEEN 1 AND 3)
);

CREATE INDEX ix_passages_quiz
    ON passages (quiz_set_id, position);

CREATE TABLE questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    passage_id BIGINT NOT NULL,
    position SMALLINT NOT NULL,
    content TEXT NOT NULL,

    CONSTRAINT fk_questions_passage
        FOREIGN KEY (passage_id) REFERENCES passages (id),

    CONSTRAINT ux_questions_passage_position
        UNIQUE (passage_id, position),

    CONSTRAINT ck_questions_position
        CHECK (position BETWEEN 1 AND 3)
);

CREATE INDEX ix_questions_passage
    ON questions (passage_id, position);

CREATE TABLE question_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL,
    position SMALLINT NOT NULL,
    content TEXT NOT NULL,

    CONSTRAINT fk_question_options_question
        FOREIGN KEY (question_id) REFERENCES questions (id),

    CONSTRAINT ux_question_options_question_position
        UNIQUE (question_id, position),

    CONSTRAINT ux_question_options_question_id
        UNIQUE (question_id, id),

    CONSTRAINT ck_question_options_position
        CHECK (position BETWEEN 1 AND 4)
);

CREATE TABLE question_keys (
    question_id BIGINT PRIMARY KEY,
    correct_option_id BIGINT NOT NULL,
    explanation TEXT NOT NULL,
    evidence TEXT,

    CONSTRAINT fk_question_keys_question
        FOREIGN KEY (question_id) REFERENCES questions (id),

    CONSTRAINT fk_question_keys_correct_option
        FOREIGN KEY (question_id, correct_option_id)
        REFERENCES question_options (question_id, id)
);

CREATE TABLE quiz_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    quiz_set_id BIGINT NOT NULL,
    score SMALLINT NOT NULL,
    completed_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_quiz_attempts_user
        FOREIGN KEY (user_id) REFERENCES app_users (id),

    CONSTRAINT fk_quiz_attempts_quiz_set
        FOREIGN KEY (quiz_set_id) REFERENCES quiz_sets (id),

    CONSTRAINT ux_quiz_attempts_user_quiz
        UNIQUE (user_id, quiz_set_id),

    CONSTRAINT ck_quiz_attempts_score
        CHECK (score BETWEEN 0 AND 9)
);

CREATE INDEX ix_quiz_attempts_quiz_score
    ON quiz_attempts (quiz_set_id, score DESC);

CREATE INDEX ix_quiz_attempts_user_completed
    ON quiz_attempts (user_id, completed_at DESC);

CREATE TABLE attempt_answers (
    attempt_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    selected_option_id BIGINT NOT NULL,
    is_correct BOOLEAN NOT NULL,

    PRIMARY KEY (attempt_id, question_id),

    CONSTRAINT fk_attempt_answers_attempt
        FOREIGN KEY (attempt_id) REFERENCES quiz_attempts (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_attempt_answers_question
        FOREIGN KEY (question_id) REFERENCES questions (id),

    CONSTRAINT fk_attempt_answers_selected_option
        FOREIGN KEY (question_id, selected_option_id)
        REFERENCES question_options (question_id, id)
);

CREATE TABLE generation_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_set_id BIGINT,
    target_date DATE,
    ai_provider VARCHAR(30),
    ai_model VARCHAR(100),
    prompt_version VARCHAR(30),
    status VARCHAR(20),
    raw_response TEXT,
    error_message TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_generation_logs_quiz_set
        FOREIGN KEY (quiz_set_id) REFERENCES quiz_sets (id)
);

CREATE INDEX ix_generation_logs_target_date
    ON generation_logs (target_date, created_at DESC);

