ALTER TABLE quiz_attempts
    ADD CONSTRAINT ux_quiz_attempts_id_user
        UNIQUE (id, user_id);

CREATE TABLE answer_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    source_attempt_id BIGINT NOT NULL,
    review_status VARCHAR(20) DEFAULT 'PENDING' NOT NULL,
    retry_count INTEGER DEFAULT 0 NOT NULL,
    last_reviewed_at TIMESTAMPTZ,
    recovered_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_answer_reviews_user
        FOREIGN KEY (user_id) REFERENCES app_users (id),

    CONSTRAINT fk_answer_reviews_question
        FOREIGN KEY (question_id) REFERENCES questions (id),

    CONSTRAINT fk_answer_reviews_source_attempt_user
        FOREIGN KEY (source_attempt_id, user_id)
        REFERENCES quiz_attempts (id, user_id),

    CONSTRAINT fk_answer_reviews_source_answer
        FOREIGN KEY (source_attempt_id, question_id)
        REFERENCES attempt_answers (attempt_id, question_id)
        ON DELETE CASCADE,

    CONSTRAINT ux_answer_reviews_user_question
        UNIQUE (user_id, question_id),

    CONSTRAINT ck_answer_reviews_status
        CHECK (review_status IN ('PENDING', 'REVIEWED', 'RECOVERED')),

    CONSTRAINT ck_answer_reviews_retry_count
        CHECK (retry_count >= 0),

    CONSTRAINT ck_answer_reviews_recovered_at
        CHECK (review_status <> 'RECOVERED' OR recovered_at IS NOT NULL)
);

CREATE INDEX ix_answer_reviews_user_status
    ON answer_reviews (user_id, review_status, last_reviewed_at DESC);

CREATE INDEX ix_answer_reviews_source_attempt
    ON answer_reviews (source_attempt_id);

CREATE INDEX ix_answer_reviews_question
    ON answer_reviews (question_id);
