ALTER TABLE generation_logs
    ADD COLUMN attempt_count INTEGER DEFAULT 0 NOT NULL,
    ADD COLUMN validation_score INTEGER,
    ADD COLUMN updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ADD COLUMN completed_at TIMESTAMPTZ;

ALTER TABLE generation_logs
    ADD CONSTRAINT ck_generation_logs_status
        CHECK (status IS NULL OR status IN (
            'GENERATING', 'VALIDATING', 'RETRYING', 'READY', 'PUBLISHED', 'FAILED', 'INVALIDATED'
        )),
    ADD CONSTRAINT ck_generation_logs_attempt_count
        CHECK (attempt_count >= 0),
    ADD CONSTRAINT ck_generation_logs_validation_score
        CHECK (validation_score IS NULL OR validation_score BETWEEN 0 AND 100);

ALTER TABLE generation_logs
    DROP CONSTRAINT fk_generation_logs_quiz_set,
    ADD CONSTRAINT fk_generation_logs_quiz_set
        FOREIGN KEY (quiz_set_id) REFERENCES quiz_sets (id) ON DELETE SET NULL;

CREATE TABLE quiz_validation_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    generation_log_id BIGINT NOT NULL,
    quiz_set_id BIGINT,
    attempt_number INTEGER NOT NULL,
    validation_type VARCHAR(20) NOT NULL,
    passed BOOLEAN NOT NULL,
    score INTEGER NOT NULL,
    issues_json JSONB DEFAULT '[]'::JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_quiz_validation_generation_log
        FOREIGN KEY (generation_log_id) REFERENCES generation_logs (id) ON DELETE CASCADE,
    CONSTRAINT fk_quiz_validation_quiz_set
        FOREIGN KEY (quiz_set_id) REFERENCES quiz_sets (id) ON DELETE SET NULL,
    CONSTRAINT ck_quiz_validation_type
        CHECK (validation_type IN ('RULE', 'AI')),
    CONSTRAINT ck_quiz_validation_attempt_number
        CHECK (attempt_number > 0),
    CONSTRAINT ck_quiz_validation_score
        CHECK (score BETWEEN 0 AND 100)
);

CREATE INDEX ix_quiz_validation_generation_log
    ON quiz_validation_results (generation_log_id, created_at);

CREATE INDEX ix_quiz_validation_quiz_set
    ON quiz_validation_results (quiz_set_id, created_at DESC);
