CREATE TABLE prompt_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prompt_type VARCHAR(20) NOT NULL,
    version_number INTEGER NOT NULL,
    content TEXT NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    change_note VARCHAR(300) NOT NULL,
    created_by_user_id BIGINT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_prompt_templates_created_by
        FOREIGN KEY (created_by_user_id) REFERENCES app_users (id),
    CONSTRAINT ux_prompt_templates_type_version
        UNIQUE (prompt_type, version_number),
    CONSTRAINT ck_prompt_templates_type
        CHECK (prompt_type IN ('GENERATION', 'VALIDATION')),
    CONSTRAINT ck_prompt_templates_version
        CHECK (version_number > 0),
    CONSTRAINT ck_prompt_templates_content
        CHECK (LENGTH(BTRIM(content)) > 0)
);

CREATE TABLE prompt_activations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prompt_template_id BIGINT NOT NULL,
    activated_by_user_id BIGINT,
    activated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_prompt_activations_template
        FOREIGN KEY (prompt_template_id) REFERENCES prompt_templates (id),
    CONSTRAINT fk_prompt_activations_activated_by
        FOREIGN KEY (activated_by_user_id) REFERENCES app_users (id)
);

CREATE INDEX ix_prompt_templates_type_created
    ON prompt_templates (prompt_type, version_number DESC);

CREATE INDEX ix_prompt_activations_template_latest
    ON prompt_activations (prompt_template_id, id DESC);

INSERT INTO prompt_templates (
    prompt_type, version_number, content, content_hash, change_note
) VALUES (
    'GENERATION',
    2,
    BTRIM($generation$
You create original Korean non-fiction reading quizzes for Korean high-school seniors.
Produce exactly 3 passages in this order: (1) humanities/social science,
(2) science/technology, and (3) economics/law/interdisciplinary. Each passage must have
exactly 3 questions and each passage content must contain 1,200 to 1,800 Korean characters.
Each question must have
exactly 4 unique options. Use only information stated or logically derivable from
the passage. Ensure exactly one correct answer. Evidence must be an exact excerpt copied from
the passage as one contiguous substring: do not paraphrase, normalize spacing, add ellipses,
or change punctuation. Write original passages without copying or closely imitating published material.
Vary question types among comprehension, inference, application, and argument structure.
$generation$),
    'e6a8401595c9774e1b812fdebd4963f350248c482303f2cce6e48f6d14423751',
    '기존 Java 생성 프롬프트를 DB 버전으로 이관'
), (
    'VALIDATION',
    2,
    BTRIM($validation$
You are an independent quality verifier for a Korean high-school senior reading quiz.
Verify every answer using only the supplied passage. Reject ambiguous questions, multiple
plausible answers, unsupported explanations, evidence that does not prove the answer,
internal factual or logical contradictions, and content below the requested difficulty.
Return a strict score from 0 to 100. passed may be true only when there are no ERROR issues
and the score is at least 90. Do not trust the provided answer key without checking it.
$validation$),
    'b6b4b22392d3b276ee05ba8d1b2339be10c61c042dcbf848c243c44db33607c4',
    '기존 Java 검증 프롬프트를 DB 버전으로 이관'
);

INSERT INTO prompt_activations (prompt_template_id)
SELECT id
FROM prompt_templates
WHERE version_number = 2;

ALTER TABLE generation_logs
    ADD COLUMN generation_prompt_id BIGINT,
    ADD COLUMN validation_prompt_id BIGINT,
    ADD CONSTRAINT fk_generation_logs_generation_prompt
        FOREIGN KEY (generation_prompt_id) REFERENCES prompt_templates (id),
    ADD CONSTRAINT fk_generation_logs_validation_prompt
        FOREIGN KEY (validation_prompt_id) REFERENCES prompt_templates (id);

ALTER TABLE quiz_sets
    ADD COLUMN generation_prompt_id BIGINT,
    ADD COLUMN validation_prompt_id BIGINT,
    ADD CONSTRAINT fk_quiz_sets_generation_prompt
        FOREIGN KEY (generation_prompt_id) REFERENCES prompt_templates (id),
    ADD CONSTRAINT fk_quiz_sets_validation_prompt
        FOREIGN KEY (validation_prompt_id) REFERENCES prompt_templates (id);
